FROM python:3.9

WORKDIR /app

RUN apt-get update && \
    apt-get upgrade -y
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --upgrade wheel
RUN pip install gradio
